from core.user_config import load_config

_config = load_config()
NEXT_PHRASE_KEY = _config['NEXT_PHRASE_KEY']
MEMORY_CUE_KEY = _config['MEMORY_CUE_KEY']
REKORDBOX_EXE_PATH = _config['REKORDBOX_EXE_PATH']
SWITCH_FOCUS_KEY = _config['SWITCH_FOCUS_KEY']
LOAD_TRACK_KEY = _config['LOAD_TRACK_KEY']
SET_CUE = _config['SET_CUE']
SAVE_CUE_AS_MEMORY_CUE = _config['SAVE_CUE_AS_MEMORY_CUE']
ADVANCE_ONE_MESURE = _config['ADVANCE_ONE_MESURE']
ADVANCE_ONE_BEAT = _config['ADVANCE_ONE_BEAT']
OPEN_SEARCH_TRACK_DIALOG = _config['OPEN_SEARCH_TRACK_DIALOG']
REKORDBOX_COLLECTION_TRACKS_XML_FILE_PATH = _config['REKORDBOX_COLLECTION_TRACKS_XML_FILE_PATH']
PLAY_PAUSE_TRACK = _config["PLAY_PAUSE_TRACK"]
LAYOUT_2_DECKS_HORIZONTAL = _config["LAYOUT_2_DECKS_HORIZONTAL"]
NEXT_TRACK_IN_COLLECTION_KEY = _config["NEXT_TRACK_IN_COLLECTION_KEY"]
PREVIOUS_TRACK_IN_COLLECTION_KEY = _config["PREVIOUS_TRACK_IN_COLLECTION_KEY"]
